{% set version = "12.1" %}

package:
  name: primesieve
  version: {{ version }}

source:
  fn: primesieve-{{ version }}.tar.gz
  url: https://github.com/kimwalisch/primesieve/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64e7f5d3ce680262b865c7aec1381ffb13d13f75dd985b964ce33806e1bbf386
  patches:
    # https://github.com/kimwalisch/primesieve/pull/146
    - pthread.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('primesieve', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    # Check libraries exist
    - test -f "${PREFIX}/include/primesieve.h"  # [unix]
    - test -f "${PREFIX}/lib/libprimesieve${SHLIB_EXT}"  # [unix]
    - if not exist %PREFIX%\\Library\\include\\primesieve.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\primesieve.dll exit 1  # [win]

    # Test CLIs.
    - primesieve -n 1

about:
  home: http://primesieve.org/
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast C/C++ prime number generator

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
