{% set version = "5.7.3" %}

package:
  name: primesieve
  version: {{ version }}

source:
  fn: primesieve-{{ version }}.tar.gz
  url: https://dl.bintray.com/kimwalisch/primesieve/primesieve-{{ version }}.tar.gz
  sha1: c8221ebe49e918523c753e644cbaa7e5389e6d04

build:
  # Seem to be encountering hangs on Windows with Python 2.7; so, they are skipped.
  skip: true  # [win and (py2k or py36)]
  number: 0
  features:
    - vc10              # [win and py34]
    - vc14              # [win and py35]
    - vc14              # [win and py36]

requirements:
  build:
    - gcc     # [unix]
    - python  # [win]

  run:
    - libgcc  # [unix]

test:
  requires:
    - python  # [win]

  commands:
    # Check libraries exist
    - test -f "${PREFIX}/lib/libprimesieve.a"      # [unix]
    - test -f "${PREFIX}/lib/libprimesieve.so"     # [linux]
    - test -f "${PREFIX}/lib/libprimesieve.dylib"  # [osx]

    # Test CLIs.
    - primesieve -n 1

about:
  home: http://primesieve.org/
  license: BSD 2-Clause
  license_file: COPYING
  summary: Fast C/C++ prime number generator

extra:
  recipe-maintainers:
    - jakirkham
