context:
  version: "12.16"

package:
  name: primesieve
  version: ${{ version }}

source:
  url: https://github.com/kimwalisch/primesieve/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 753530ec2b4cbf3b62808b0661ab00e0382d47bded8a57c4fe41a6a4409f7c94

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage('primesieve', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - primesieve.h
      lib:
        - primesieve
  - script:
      # Test CLIs.
      - primesieve -n 1

about:
  homepage: http://primesieve.org/
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast C/C++ prime number generator

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
