travis:
  secure:
    BINSTAR_TOKEN: BDakVu6wBHW6Q49e3iPCh8OBmQ5LAF6oUzbZtXH3zgNbXYmuO0VeWUZOH3DeGooZx9rAAERN06UDDagHamRPWoplNajYxlQxZHjqnTsU274jHg3A90l2gwHdPhW7JyHfPGkwrRI06f10OcHmFHov4tdjnWdmBlRnRohZNqITkV6BeCTtMEZ9O7ki44gkn5sR/YuvgQkr2oYU3v2ZKJzSuuGwZlwUu1CqgoA1LmKok8aqttYudL3/ubhaXIkatUNs2AioBWQ8nQWGHM1mIvNMjpdZF/aW9/1Tfc9VU5RV5+j5lCWwPS1R+r03+SeP3OnLjTS4/wMZ/+LnhvrwdGaifWU1e8cRJAtJFtiOKudlKpChbqaXuHyHVh9CXz5LkAw8Zo8jOQW2JxOFBI0oq6/YLR0DzmQnhATGUJ7SNV2HBuuAwu31C8CSlgpv2VMqTVseW8lhdFc8JJoCVr3danD3bNHSzLhjRIeSNSNR4PASOhqr5BbO+bhrxxYzGWi4DeTHrZzYqG3i8+GYZ2shKJR+JBJgHNmjwX8lEVUfp7y3PxUdGGfJnX0Y3aR4DnRtkdMpWzxalDXu5ZInKNYwz4YTbEGzHQS1i1sUohqn7+vk6EN327x1leypgt8hzYI/PS1LDJ2LFWJcd/YAdeiQYVOWglysMUSz2gTibxV2YBiyO5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
