travis:
  secure:
    BINSTAR_TOKEN: AFsPelQPF7by4p2NmEPX4LPzWwnRtFfPYehHu8xAPG4Bj4rbbATC3ZdGsGovoVNQEnKYNyKUeGe6+yzbOh4ugTXY+BhcFcAXdV1h6egooCRgo3vRZXhtOnRJQa/euPx3tjd1CbFyGqI6ooiklDIi7ZAVZJBPQirO4Rw7FYVhomLeYR25mYVxHGLBMdhRBx8QB7NwMZo0Hi0isydxEHUjGC9T+LYTyz75QqiWYQ2A31D3GZKrwT6jhh9aUPOYglDfyHtaQsQ9a5arfeSXrxHbMxlxVqoqXzbkUZqLXmiqMadLjJYdpnHEgLovCOYmR43g16rXuROvZLWt0+Sx152TItc2vRMRQgpR4bql42BGK7ugLoAECj+QD6rgD88m9AUzVO8C7qYjwI/ITuGr4fT/upPbpu1Cbr18QiHtLoK2iBvibGhWO3jBMT+Au3VNLfT3Krar/R3ckCksabDqITlY7Y83p2Qcxs+RsYMAM0tWef2F2MMlo2sYHXQdw3B415K/G5YQrpPtLOX1ltODkhM41Qx7YafDKgUKFv1c0kVTiL5npH+2C76qqciNkmf6XJmBr9vKq2vvNKezdRvuMFdZj2WOn6J+IjBwXIEwkz5SeP6WzoF+mZZPb6IIzia96cBqYV7BaQ1pa2o/wiNJcSeWUuw9R330VTNqj+287B4EYqo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
